<a href="https://colab.research.google.com/github/chw8207/python-seminar/blob/main/2%EC%9B%943%EC%9D%BC_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 정수 -50~50 범위의 난수로 이뤄진 (4, 5)형태의 numpy.array를 출력하고 
# 행을 기준으로 오름차순 정렬한 결과와 1차원 배열로 변경하여 
# 오름차순 정렬한 결과를 출력하시오.

In [ ]:
# 라이브러리 임포트
import numpy as np

# seed값 설정
np.random.seed(1)

# 난수로 이뤄진 (4,5)형태의 배열 출력
arr = np.random.randint(-50,50, size=(4,5))
print(arr)

[[-13 -38  22 -41  25]
 [-45  29  14 -34 -49]
 [ 26  21 -44 -25   0]
 [-30 -32  34 -39 -22]]


In [ ]:
# 행을 기준으로 오름차순 정렬
np.random.seed(1)
print(np.sort(arr, axis=0))

[[-45 -38 -44 -41 -49]
 [-30 -32  14 -39 -22]
 [-13  21  22 -34   0]
 [ 26  29  34 -25  25]]


In [ ]:
# 1차원 배열로 변경하여 오름차순 정렬
np.random.seed(1)
arr2 = np.ravel(arr)
print(np.sort(arr2))

[-49 -45 -44 -41 -39 -38 -34 -32 -30 -25 -22 -13   0  14  21  22  25  26
  29  34]


In [ ]:
# 다음 두 행렬에 대하여 내적 연산을 수행한 결과값을 출력하시오.
# (단, 소수점 아래는 제거한다.)
import numpy as np

a = [[2.1,3.5], [4.2,2.7], [2.3, 1.9]]
b = [[5,2,3], [1,3,5]]
print(np.trunc(np.dot(a,b)))

[[14. 14. 23.]
 [23. 16. 26.]
 [13. 10. 16.]]


In [ ]:
# 1. 원소가 모두 3인 (3, 4, 5)형태의 numpy.array를 출력
print(np.full([3,4,5],3))

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [ ]:
# 6. 다음 패턴 출력하기
# 0 1 0 1
# 1 0 1 0
# 0 1 0 1
# 1 0 1 0

In [16]:
import numpy as np
arr = [[0 if i%2==0 and j%2==0 else 1 for j in range(5)] for i in range(5)]

print(np.array(arr))

[[0 1 0 1 0]
 [1 1 1 1 1]
 [0 1 0 1 0]
 [1 1 1 1 1]
 [0 1 0 1 0]]
