<a href="https://colab.research.google.com/github/chw8207/python-seminar/blob/main/2%EC%9B%943%EC%9D%BC_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# 정수 -50~50 범위의 난수로 이뤄진 (4, 5)형태의 numpy.array를 출력하고 
# 행을 기준으로 오름차순 정렬한 결과와 1차원 배열로 변경하여 
# 오름차순 정렬한 결과를 출력하시오.

In [ ]:
# 라이브러리 임포트
import numpy as np

# seed값 설정
np.random.seed(1)

# 난수로 이뤄진 (4,5)형태의 배열 출력
arr = np.random.randint(-50,50, size=(4,5))
print(arr)

[[-13 -38  22 -41  25]
 [-45  29  14 -34 -49]
 [ 26  21 -44 -25   0]
 [-30 -32  34 -39 -22]]


In [ ]:
# 행을 기준으로 오름차순 정렬
np.random.seed(1)
print(np.sort(arr, axis=0))

[[-45 -38 -44 -41 -49]
 [-30 -32  14 -39 -22]
 [-13  21  22 -34   0]
 [ 26  29  34 -25  25]]


In [ ]:
# 1차원 배열로 변경하여 오름차순 정렬
np.random.seed(1)
arr2 = np.ravel(arr)
print(np.sort(arr2))

[-49 -45 -44 -41 -39 -38 -34 -32 -30 -25 -22 -13   0  14  21  22  25  26
  29  34]


In [ ]:
# 다음 두 행렬에 대하여 내적 연산을 수행한 결과값을 출력하시오.
# (단, 소수점 아래는 제거한다.)
import numpy as np

a = [[2.1,3.5], [4.2,2.7], [2.3, 1.9]]
b = [[5,2,3], [1,3,5]]
print(np.trunc(np.dot(a,b)))

[[14. 14. 23.]
 [23. 16. 26.]
 [13. 10. 16.]]


In [ ]:
# 1. 원소가 모두 3인 (3, 4, 5)형태의 numpy.array를 출력
print(np.full([3,4,5],3))

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [ ]:
# 6. 다음 패턴 출력하기
# 0 1 0 1
# 1 0 1 0
# 0 1 0 1
# 1 0 1 0

In [2]:
import numpy as np
arr = [[0 if i%2==0 and j%2==0 else 1 for j in range(4)] for i in range(4)]

print(np.array(arr))

[[0 1 0 1]
 [1 1 1 1]
 [0 1 0 1]
 [1 1 1 1]]


In [13]:
# 4. 주어진 배열을 행을 기준으로 3개로 분할하여 분할된 각 배열의 원소들을
# 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합하시오.
# (단, 출력 결과는 원본 배열의 차원과 같아야함.)
import numpy as np

arr = np.arange(2,20,2).reshape((3,3))
print(arr)
print(arr.ndim)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
2


In [10]:
# 행 기준으로 3개 분할
arr_vsplit = np.vsplit(arr,3)
print(arr_vsplit)

[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]


In [14]:
# 각 배열의 원소들을 제곱하기
arr_square = np.square(arr_vsplit)
print(arr_square)
print(arr.ndim)

[[[  4  16  36]]

 [[ 64 100 144]]

 [[196 256 324]]]
2


In [37]:
# 5. 삼각함수의 특수각(0, 30, 60, 90)을 numpy.array로 생성한 후 
# 이에 해당하는 sin, cos, tan값을 구하여 수한 값을 list에 담아 출력하시오.
# (단, 값이 무한대이면 "INF"를 출력하며, numpy에서 삼각함수는 radian 값을 사용함
# (radian= degree*pi/180))
import numpy as np

arr = np.array([0,30,60,90])
tf1 = []
tf2 = []
tf3 = []

for i in range(len(arr)) : 
  radian = arr[i]*np.pi/180
  tf1.append(np.sin(radian))
  tf2.append(np.cos(radian))
  tf3.append(np.tan(radian))
print('sin값', tf1)
print('cos값', tf2)
print('tan값', tf3)

sin값 [0.0, 0.49999999999999994, 0.8660254037844386, 1.0]
cos값 [1.0, 0.8660254037844387, 0.5000000000000001, 6.123233995736766e-17]
tan값 [0.0, 0.5773502691896257, 1.7320508075688767, 1.633123935319537e+16]
