<a href="https://colab.research.google.com/github/chw8207/python-seminar/blob/main/2%EC%9B%943%EC%9D%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 넘파이(Numpy)

In [2]:
import numpy as np

In [20]:
# 1차원 배열
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [11]:
type(arr)

numpy.ndarray

In [8]:
# 2차원 배열
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
type(arr)

numpy.ndarray

In [14]:
# tuple로 배열 만들기
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)

[4 5 6]


In [13]:
# list로 배열 만들기
lst = [1,2,3]
arr = np.array(lst)
print(arr)

[1 2 3]


In [15]:
lst2 = [[1,2,3],[4,5,6]]
arr2 = np.array(lst2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr.shape)
print(arr2.shape)

(3,)
(2, 3)


In [17]:
# size : 원소의 개수
print(arr.size, arr2.size)

3 6


In [21]:
# dtype : 데이터 타입 확인
# astype : 데이터 타입 변경
arr = arr.astype(np.float32)
print(arr, arr.dtype)

[1. 2. 3.] float32


In [19]:
arr = np.array([1,2,3.4,4,'64'], dtype=int)
print(arr, arr.dtype)

[ 1  2  3  4 64] int64


In [22]:
arr = np.array([1,2,3.4,4,'hello'], dtype=int) 
print(arr, arr.dtype)

ValueError: ignored