<a href="https://colab.research.google.com/github/chw8207/python-seminar/blob/main/2%EC%9B%943%EC%9D%BC_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 정수 -50~50 범위의 난수로 이뤄진 (4, 5)형태의 numpy.array를 출력하고 
# 행을 기준으로 오름차순 정렬한 결과와 1차원 배열로 변경하여 
# 오름차순 정렬한 결과를 출력하시오.

In [2]:
# 라이브러리 임포트
import numpy as np

# seed값 설정
np.random.seed(1)

# 난수로 이뤄진 (4,5)형태의 배열 출력
arr = np.random.randint(-50,50, size=(4,5))
print(arr)

[[-13 -38  22 -41  25]
 [-45  29  14 -34 -49]
 [ 26  21 -44 -25   0]
 [-30 -32  34 -39 -22]]


In [ ]:
# 행을 기준으로 오름차순 정렬
